# Site settings
description: Personal Blog and Data Repository - Hrishi Olickel
#baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://hrishioa.github.io" # the base hostname & protocol for your site
# url: "http://localhost:3000" # the base hostname & protocol for your site
title: "Hrishi Olickel"

# User settings
username: hrishioa
user_description: Building maritime risk intelligence tools at Greywing.
user_title: Hrishi Olickel
email: hrishi[at]grey-wing.com
github_username:  hrishioa
disqus_username: hrishioa
future: false
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
